"""Add location to CompanyOffers

Revision ID: 204b0cc5b2bd
Revises: 
Create Date: 2024-11-28 09:23:03.782575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '204b0cc5b2bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_offers', sa.Column('description', sa.String(), nullable=False))
    op.add_column('company_offers', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'company_offers', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company_offers', type_='foreignkey')
    op.drop_column('company_offers', 'location_id')
    op.drop_column('company_offers', 'description')
    # ### end Alembic commands ###
