"""Fix relationship name in ProfessionalProfile

Revision ID: 9d20e37651f8
Revises: 86dea6ae1a4b
Create Date: 2024-11-28 10:56:14.122324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d20e37651f8'
down_revision: Union[str, None] = '86dea6ae1a4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
