"""Add ondelete cascade to company_offers_id in RequestsAndMatches

Revision ID: e44d4f1adcb2
Revises: c178749bc1c6
Create Date: 2024-12-08 22:24:23.125508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e44d4f1adcb2'
down_revision: Union[str, None] = 'c178749bc1c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('company_offers_company_id_fkey', 'company_offers', type_='foreignkey')
    op.create_foreign_key(None, 'company_offers', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('requests_and_matches_company_offers_id_fkey', 'requests_and_matches', type_='foreignkey')
    op.drop_constraint('requests_and_matches_professional_profile_id_fkey', 'requests_and_matches', type_='foreignkey')
    op.create_foreign_key(None, 'requests_and_matches', 'company_offers', ['company_offers_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'requests_and_matches', 'professional_profile', ['professional_profile_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requests_and_matches', type_='foreignkey')
    op.drop_constraint(None, 'requests_and_matches', type_='foreignkey')
    op.create_foreign_key('requests_and_matches_professional_profile_id_fkey', 'requests_and_matches', 'professional_profile', ['professional_profile_id'], ['id'])
    op.create_foreign_key('requests_and_matches_company_offers_id_fkey', 'requests_and_matches', 'company_offers', ['company_offers_id'], ['id'])
    op.drop_constraint(None, 'company_offers', type_='foreignkey')
    op.create_foreign_key('company_offers_company_id_fkey', 'company_offers', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###
